### ISSUE TITLE
Azure FileStorage

### ISSUE THREAD

**Issue by wesleyemery** [Azure-Terraform/terraform-azurerm-storage-account#3]
This module does not have the ability to deploy using account_kind = FileStorage. The Blob properties conflict with the ability to deploy using File Storage. Here is an example of what I did with MBS: 

esource "azurerm_storage_account" "sa" {
  name                     = var.storage_account_name
  resource_group_name      = var.windows_resource_group
  location                 = var.location
  account_kind             = "FileStorage"
  account_tier             = "Premium"
  account_replication_type = "LRS"
  access_tier              = var.access_tier
  is_hns_enabled           = var.enable_hns
  large_file_share_enabled = var.enable_large_file_share

  allow_blob_public_access  = var.allow_blob_public_access
  enable_https_traffic_only = var.enable_https_traffic_only
  min_tls_version           = var.min_tls_version

  tags = module.metadata.tags

  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_storage_share" "ss" {
  name = var.share_name
  storage_account_name = azurerm_storage_account.sa.name
}

It may also be useful to include an example usage of a file share deployment.

**Comment by dutsmiller** [comment]
https://github.com/Azure-Terraform/terraform-azurerm-storage-account/releases/tag/v0.4.1
